<a href="https://colab.research.google.com/github/gulshan-katankar/language_modelling/blob/main/model_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import requests

url = "https://raw.githubusercontent.com/gulshan-katankar/language_modelling/refs/heads/main/names.txt"

words = requests.get(url).text.splitlines()

In [3]:
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
len(words)

32033

In [5]:
#build the vocab of characters and mappings

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [7]:
# build the dataset

block_size = 3 # context length: how many characters do we tako to predict the next one?
x, y = [], []
for w in words [:5] :

  print(w)
  context = [0] * block_size #start with the padded context of 0
  for ch in w + '.': #iterate over all the char
    ix = stoi[ch]
    x. append(context) #stores the context
    y.append(ix) #stores the labels for the context
    print(''.join(itos[i] for i in context), ' -- >', itos[ix])
    context = context [1:] + [ix] # crop and append

x = torch. tensor(X)
y = torch. tensor(Y)

emma
...  -- > e
..e  -- > m
.em  -- > m
emm  -- > a
mma  -- > .
olivia
...  -- > o
..o  -- > l
.ol  -- > i
oli  -- > v
liv  -- > i
ivi  -- > a
via  -- > .
ava
...  -- > a
..a  -- > v
.av  -- > a
ava  -- > .
isabella
...  -- > i
..i  -- > s
.is  -- > a
isa  -- > b
sab  -- > e
abe  -- > l
bel  -- > l
ell  -- > a
lla  -- > .
sophia
...  -- > s
..s  -- > o
.so  -- > p
sop  -- > h
oph  -- > i
phi  -- > a
hia  -- > .


/tmp/ipykernel_795/1879530691.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch. tensor(X)
/tmp/ipykernel_795/1879530691.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch. tensor(Y)


In [8]:
x.shape, x.dtype, y.shape, y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

from 5 words we have a dataset of 32 examples, where each neural net have an input of size 3 they are integers

the labels too are integers

In [9]:
x

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [10]:
y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [11]:
c = torch.randn((27,2)) #this is the embedding table, every char will have a 2 dim embedding

In [12]:
c #this is randomly generated as a model param, and will be optimized further

tensor([[ 1.2832e+00, -5.5841e-01],
        [-1.7665e-01,  1.3457e+00],
        [ 1.2621e+00,  2.9356e-01],
        [-1.8683e-01, -3.9807e-01],
        [ 1.8270e-01, -4.9373e-01],
        [-1.2772e+00,  1.3232e+00],
        [-4.7474e-02, -2.0602e-01],
        [ 5.3236e-02,  1.4040e+00],
        [ 4.1752e-01, -9.7645e-02],
        [ 1.3166e+00, -2.6769e-01],
        [-2.1983e-03,  2.2881e-01],
        [ 1.3150e+00, -5.3842e-01],
        [ 2.5157e-02,  2.6276e+00],
        [-3.0813e-01,  1.8799e+00],
        [ 2.9645e-02, -5.1233e-01],
        [ 2.4169e+00, -3.9956e-01],
        [-1.1479e+00, -2.0835e-01],
        [ 9.6115e-01,  1.2409e+00],
        [ 8.6723e-02, -6.6782e-01],
        [-2.9608e-01,  9.3969e-01],
        [ 1.9885e-01,  4.4112e-01],
        [-4.8309e-01, -1.1641e+00],
        [-7.5322e-01,  5.6410e-01],
        [ 1.3311e+00,  7.4322e-01],
        [-2.8638e-02, -8.0578e-01],
        [ 3.1049e-01,  4.9216e-01],
        [ 4.5438e-01,  3.2429e+00]])